### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by triniwiz** [xmpp-ftw/xmpp-ftw-register#12]
So i've tried to register using the demo also from the console from the web browser and in the demo i'm seeing 

 IN:  xmpp.register.set out Object {to: "myserver.com", form: Array[1]} true
demo.js:238 OUT:  (id=14) xmpp.register.set Object {to: "myserver.com", form: Array[1]}

but it's not creating any account on the server and the in band registration works because i tested it from the converse.org website... would love to get this working because im trying to use xmpp-ftw + ionic for a mobile app ^_^

i'm using prosody .10

**Comment by lloydwatkin** [comment]
What do the logs say in Prosody? I've used this to register several accounts for demos so I'd imagine there's something going on in the setup (hopefully anyway).

**Comment by triniwiz** [comment]
well prosody isn't loggin anything to do with registering this is the code i use to test the registration

 socket.send(
                        'xmpp.register.set',
                        {
                            "to": "localhost",
                            "form" : [{
                                "email": "test@localhost",
                                "username": "showstopper",
                                "password": "test"
                            }]
                        }

**Comment by lloydwatkin** [comment]
Prosody should log something even if the registration failed. Have you got logging level set to 'debug'? Have you checked both the standard log and the error one?

Lastly your register call with email and password is slightly off, please see https://xmpp-ftw.jit.su/manual/in-band-registration/#register for an example.

**Comment by triniwiz** [comment]
i tried the examples but nothing works if i try the xmpp.register.get the callback never runs another strange thing is that everything works fine if i try using conversejs.org 

the get code 

 socket.send(
                 'xmpp.register.get',
                 {
                 "to": "chatome.com"
                 },
                 function(error, data) { console.log(error, data) }
                 )

the reg code 


 socket.send(
                        'xmpp.register.set',
                        {
                            "to": "chatome.com",
                            "email": "test@test.com",
                            "username": "showstopper",
                            "password": "test",
                             "form":[]
                        },
                        function(error, data) {
                            console.log(error, data) }
                    )

**Comment by lloydwatkin** [comment]
Ahh are you trying to register with the server without having a connection open?

Probably you are after something like:

```javascript
socket.send(
  'xmpp.login',
  {
    jid: 'showstopper@chatome.com',
    password: 'password',
    register: true
  }
})
```

**Comment by triniwiz** [comment]
wow that worked :+1:  well now i can't unregister the user if i register them with xmpp-ftw :(

**Comment by robotnic** [comment]
The register parameter is not documented.

**Comment by lloydwatkin** [comment]
https://github.com/lloydwatkin
